### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by rexthecoder** [Hawmex/dawn#13]
I want to build a landing page with this framework, but it seems the widget is not more,

Is there and contribution guide? I want to help you build more widgets. We can chat on twitter

**Comment by Hawmex** [comment]
Thank you for helping.

I definitely have to add a contribution guideline to the repo. Meanwhile, can you list what widgets you'd like to be added?

**Comment by Hawmex** [comment]
You can also propose your ideas on #11
