### ISSUE TITLE
Hot restart turn to add multiple widget not to the element tree 

### ISSUE THREAD

**Issue by rexthecoder** [Hawmex/dawn#14]
This is a simple widget, but when you click on the hot restart, it turns out to add more elements to the tree
Below is a video to reproduce the effect

https://user-images.githubusercontent.com/36260221/189105951-405ccc48-86e1-40b6-91c2-faac0e67ddec.mp4

**Comment by Hawmex** [comment]
Can you please provide your `launch.json`?

**Comment by rexthecoder** [comment]
This is my launch file @Hawmex 
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "program": "web/main",
            "name": "awesome",
            "request": "launch",
            "type": "dart"
        }
    ]
}
```

**Comment by Hawmex** [comment]
It seems like you're using `webdev`. It isn't supported yet. Instead, please use `dawn compile -s` command for now.

> ## Start The Development Environment
> Now, we can edit the `/web` directory in our project. To see the changes, we can run a development server using Dawn CLI.
> ```
> dawn compile -s
> ```

**More information about Dawn CLI is available on the website (CLI Docs section).**

**Comment by Hawmex** [comment]
Please close this if it's fixed.

**Comment by rexthecoder** [comment]
Unhandled exception:
FileSystemException: Deletion failed, path = './.dawn/dev' (OS Error: No such file or directory, errno = 2)
#0      _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:427:7)

**Comment by Hawmex** [comment]
> Unhandled exception: FileSystemException: Deletion failed, path = './.dawn/dev' (OS Error: No such file or directory, errno = 2) #0 _Directory._deleteSync (dart:io/directory_impl.dart:201:7) #1 FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:427:7)

Can you please update Dawn to `5.6.1` and confirm that this is fixed?

**Comment by rexthecoder** [comment]
it works now, you can close it

**Comment by rexthecoder** [comment]
I am working on a landing page. I will let you know what I come up with.
