### ISSUE TITLE
Add a warning when JS is disabled

### ISSUE THREAD

**Issue by flexagoon** [Hawmex/dawn#17]
Currently if you visit a page made with Dawn with Javascript disabled in your browser, you'll just see a blank page. There should be a warning, something like "this page needs Javascript to work", when JS is disabled. This is possible to do with the HTML `<noscript>` tag.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript

**Comment by Hawmex** [comment]
This is fixed in 6.0.2 release, @flexagoon.
