### ISSUE TITLE
Differences, compared to Jaspr

### ISSUE THREAD

**Issue by gintominto5329** [Hawmex/dawn#19]
Hello,

We needed an in-dart, web framework urgently,

So may I ask, for some of the **core** differences, between [Dawn](https://pub.dev/packages/dawn)(we), and [Jaspr](https://pub.dev/packages/jaspr),

thanks

**Comment by Hawmex** [comment]
Jaspr is SSR-first, while Dawn currently only supports CSR. However, Dawn is extremely extensible in every aspect. So, one could implement SSG and SSR (& hydration) for Dawn in separate packages.

Jaspr also supports strongly typed styling, if I'm not wrong.

TLDR; Dawn is more of a minimal yet extensible library like React, while Jaspr could be considered a framework.

If there are no further questions, please consider closing this issue.
