### ISSUE TITLE
Are you interested in about contributing into Jaspr?

### ISSUE THREAD

**Issue by mjablecnik** [Hawmex/dawn#4]
Hello, I found this package very interesting for creating web pages with Dart. :-)

But with `dawn` also exists a lot of other web frameworks inspired by Flutter which you can use for creating of web pages.
For example I am using and contributing into this project: https://github.com/schultek/jaspr which is very similar to `dawn`
and I think it can be time losting when more people work on same thing more times..

So I would like to ask you if are you not interested into join to our growing community of developers around `Jaspr` project 
and make one great Dart Web framework together?

I work on this PR: https://github.com/schultek/jaspr/pull/13 right now.
And for better communication we are using also Discord: https://discord.gg/G8pH8X4u
So if you would like to join to us, so you are welcome ;-)

**Comment by Hawmex** [comment]
Hello @mjablecnik. I took a look at `jaspr` and it is indeed great (SSR especially). But I think `jaspr` and `dawn` are aiming at different things. `jaspr` is kind of like `next` and `dawn` is like `create-react-app`. I honestly prefer `dawn`'s widget model and its less complexity overall (by complexity I mean implementing SSR, being a mono-repo, etc.).

But I would like to help with `jaspr` while I also keep working on `dawn`.
